/* USER CODE BEGIN Header */
/**
  *********************************************************************************************************
  * @file           : main.c
  * @brief          : Program used for RMS current measurement using FIR type SAL and CAL digital filters.
  * 				  The user receives the current value through a serial terminal, each time he presses
  * 				  the user button on the board.
  * 				  The current transformer (CT) used is a Non-invasive AC current sensor (100A max)
  * 				  Model SCT-013-000.
  *********************************************************************************************************
  * @attention
  *
  * Copyright (c) 2022 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
/* Private includes ----------------------------------------------------------*/
#include "main.h"
#include "API_delay.h"		/*API for implementing non-blocking delays*/
#include "API_uart.h"		//API for UART management
#include "API_debounce.h"	//API to implement software anti-rebounce
#include "API_adc.h"		//API for ADC handling
#include "API_timer.h"		//API for TMR10 management
#include "API_rms.h"		//API to measure the RMS current value
/* Private typedef -----------------------------------------------------------*/

/* FSM states in infinite loop of main program */
typedef enum
{
	IDLE=0,
	READ_RMS_CURRENT,
	SEND_DATA,
	RESTART
} rmsCurrentFSMState_t;

rmsCurrentFSMState_t currentFSMState;

/* Handler declarations for ADC, TImer and UART modules */

TIM_HandleTypeDef htim10;

UART_HandleTypeDef huart1;

ADC_HandleTypeDef hadc1;
/* Private define ------------------------------------------------------------*/
#define LENGTH_DATA				10U		//Maximum size for custom messages containing the RMS current value
#define LENGTH_SMS				15U		//Maximum size for custom messages of valid or invalid data
#define LENGTH_STATE			50U		//Maximum size for custom messages of of each state of the FSM
#define BAUDS					9600L
#define RESOLUTION_ADC			12U
#define MAX_CURRENT_VALUE		100.0F
#define MIN_CURRENT_VALUE		0.0F
/* Private macro -------------------------------------------------------------*/
/* Private variables ---------------------------------------------------------*/
const char fsmState1[LENGTH_STATE]= "State IDLE: Key Pressed\r\n";
const char fsmState2[LENGTH_STATE]= "State READ_RMS_CURRENT: Get RMS Current - ";
const char fsmState3[LENGTH_STATE]= "State SEND_DATA: Irsm: ";
const char fsmState4[LENGTH_STATE]= "State RESTART: -------\r\n";
const char validData[LENGTH_SMS]="Validate Data\r\n";
const char invalData[LENGTH_SMS]="Invalid Data\r\n";
const char initTimer[LENGTH_STATE]="TIMER10 successful configuration\r\n";

float irms_line;			//variable to store the RMS current data returned by the API_rms.
char irmsStr[LENGTH_DATA];	//variable to store the RMS current value to be sent by the UART.

/* Private function prototypes -----------------------------------------------*/
static void SystemClock_Config(void);
static void Error_Handler(void);

/* Private user code ---------------------------------------------------------*/
/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
	memset(irmsStr,'\0',sizeof(irmsStr)); /*Data vector initialization*/

	/* MCU Configuration--------------------------------------------------------*/

	/* Reset of all peripherals, Initializes the Flash interface and the Systick. */
	HAL_Init();
	__HAL_RCC_GPIOH_CLK_ENABLE();
	/* Configure the system clock */
	SystemClock_Config();

	/* Initialize all LEDS */
	BSP_LED_Init(LED_USER);
	BSP_LED_Init(LED1);
	BSP_LED_Init(LED2);

	BSP_PB_Init(BUTTON_USER, BUTTON_MODE_GPIO);	//Initialize push button */
	BSP_TICK_Init();	//Initialize of the GPIO used to verify the sampling time generated by the TMR10 interrupt

	/* Initialize UART*/
	if(uartInit(&huart1,BAUDS) == false)
		Error_Handler();

	/* Initialize ADC*/
	if(adcInit(&hadc1,RESOLUTION_ADC,&huart1) == false)
		Error_Handler();

	/* Initialize Timer*/
	if(timerInit(&htim10) == true)
		uartSendString(&huart1,(uint8_t *)initTimer);
	else
		Error_Handler();

	/* Initialization of FSM */
	currentFSMState = IDLE;					//initialize the main FSM
	debounceFSM_init();						//initialize the FSM for anti-rebounds

	if(rmsFSM_init(&htim10,&hadc1,&huart1) == false)	//initialize the FSM for RMS current calculation
		Error_Handler();

	while (1)
	{
		/* USER CODE END WHILE */
		rmsFSM_update();

		switch (currentFSMState)
		{
			/***********************************************************************************
			 * State: IDLE
			 * In this state it waits for the user to press the button on the board.
			 * The user led on the board lights up as an indication of remaining in this state.
			 * *********************************************************************************/
			case IDLE:
				debounceFSM_update();

				if (readKey())
				{
					uartSendString(&huart1,(uint8_t *)fsmState1);
					BSP_LED_Off(LED_USER);
					currentFSMState = READ_RMS_CURRENT;
				}
				else
					BSP_LED_On(LED_USER);
				break;

			case READ_RMS_CURRENT:
				uartSendString(&huart1,(uint8_t *)fsmState2);
				irms_line = readRMSCurrent();	//get value RMS current

				/*****************************************************************************************
				 *Validation of the data returned by the API_rms.
				 *If a negative value is received or outside the maximum measurement range of the sensor,
				 *we discard the data and send a message to the user indicating that the measured value
				 *is incorrect and restart the FSM.
				 *Otherwise, we continue to the next state to send the value to the user through the UART.
				 ****************************************************************************************/
				if(irms_line >= MIN_CURRENT_VALUE && irms_line <MAX_CURRENT_VALUE)
				{
					uartSendString(&huart1,(uint8_t *)validData);
					currentFSMState = SEND_DATA;
				}
				else
				{
					uartSendString(&huart1,(uint8_t *)invalData);
					currentFSMState = RESTART;
				}
				break;

			case SEND_DATA:
				sprintf(irmsStr,"%5.2fA\r\n",irms_line);
				uartSendString(&huart1, (uint8_t *)fsmState3);
				uartSendString(&huart1, (uint8_t *)irmsStr);
				currentFSMState = RESTART;
				break;

			case RESTART:
				memset(irmsStr,'\0',sizeof(irmsStr));
				uartSendString(&huart1, (uint8_t *)fsmState4);
				currentFSMState = IDLE;
				break;

			default:
				timerStop(&htim10);
				Error_Handler();
				break;
		}
	}
}


/**
  * @brief System Clock Configuration
  * @retval None
  */
static void SystemClock_Config(void)
{
	RCC_OscInitTypeDef RCC_OscInitStruct = {0};
	RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

	/** Configure the main internal regulator output voltage
	 */
	__HAL_RCC_PWR_CLK_ENABLE();
	__HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

	/** Initializes the RCC Oscillators according to the specified parameters
	 * in the RCC_OscInitTypeDef structure.
	 */
	RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
	RCC_OscInitStruct.HSEState = RCC_HSE_ON;
	RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
	RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
	RCC_OscInitStruct.PLL.PLLM = 25;
	RCC_OscInitStruct.PLL.PLLN = 120;
	RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
	RCC_OscInitStruct.PLL.PLLQ = 4;
	if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
	{
		Error_Handler();
	}

	/** Initializes the CPU, AHB and APB buses clocks
	 */
	RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
			|RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
	RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
	RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
	RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
	RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

	if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_1) != HAL_OK)
	{
		Error_Handler();
	}
}

/* USER CODE BEGIN 4 */
/**
  * @brief  Timer overflow interrupt routine, used to generate a sampling time Ts= 4.16ms
  * 		corresponding to a sampling frequency of Fs=240Hz, required by the API_rms
  * 		for the calculation of the digital filters SAL and CAL.
  * @retval None
  */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
	/*Check if it is the interruption caused by Timer 10 and call the getSamples routine of the API_rms*/
	if(htim == &htim10)
		getSamples();
}

/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
static void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */

  BSP_LED_On(LED1);	//Led 1 indicates that an error occurred in the execution of the main program.
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
